"""add cancelled task status

Revision ID: 7670f727fabd
Revises: 06babc3c066f
Create Date: 2026-02-10 20:03:47.369986

Why this migration exists:
- `Task.status` is stored as a PostgreSQL ENUM.
- Adding a new Python enum value does NOT automatically update the DB enum type.
- This migration explicitly adds the enum value "cancelled" in Postgres.

Production notes:
- Extending a Postgres enum is done via: ALTER TYPE <enum> ADD VALUE '<value>';
- Removing enum values is non-trivial in Postgres; downgrade is intentionally a no-op.
- We defensively handle different enum type names across environments:
    * New code explicitly names the enum type "task_status" (recommended).
    * Older DBs may have an auto-generated type name like "taskstatus".
"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7670f727fabd"
down_revision: Union[str, None] = "06babc3c066f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Add the "cancelled" value to the Postgres enum type backing Task.status.

    We try the recommended type name first ("task_status"). If the DB was created
    before we started explicitly naming the enum, SQLAlchemy may have created an
    auto-generated type name (commonly "taskstatus"). We handle both.

    This migration is idempotent:
    - It will not fail if the value already exists.
    - It will no-op if neither enum type exists (which would indicate a schema mismatch).
    """
    op.execute(
        """
        DO $$
        DECLARE
            enum_type text;
        BEGIN
            -- Prefer the explicit, production-friendly enum type name used by current code.
            IF EXISTS (SELECT 1 FROM pg_type WHERE typname = 'task_status') THEN
                enum_type := 'task_status';
            ELSIF EXISTS (SELECT 1 FROM pg_type WHERE typname = 'taskstatus') THEN
                -- Backward-compat: type name likely auto-generated by SQLAlchemy in older schema.
                enum_type := 'taskstatus';
            ELSE
                -- Neither type exists; nothing to migrate (or schema is not what we expect).
                RETURN;
            END IF;

            -- Add enum value only if it's missing.
            IF NOT EXISTS (
                SELECT 1
                FROM pg_type t
                JOIN pg_enum e ON t.oid = e.enumtypid
                WHERE t.typname = enum_type
                  AND e.enumlabel = 'cancelled'
            ) THEN
                EXECUTE format('ALTER TYPE %I ADD VALUE %L', enum_type, 'cancelled');
            END IF;
        END
        $$;
        """
    )


def downgrade() -> None:
    """
    Downgrade is intentionally a no-op.

    Reason:
    - PostgreSQL does not support dropping an enum value via a simple ALTER TYPE.
    - Proper rollback requires creating a new enum type without the value,
      migrating the column to it, dropping the old type, then renaming.

    If you truly need to remove "cancelled", the safe approach is:
      1) CREATE TYPE <new_enum> AS ENUM (... without 'cancelled' ...)
      2) ALTER TABLE tasks ALTER COLUMN status TYPE <new_enum> USING status::text::<new_enum>
      3) DROP TYPE <old_enum>
      4) ALTER TYPE <new_enum> RENAME TO <old_enum>
    """
    pass
